language: node_js

node_js:
  - "7"

sudo: false

before_install:
  - npm --prefix=frontend/ config set spin false

install:
  - npm --prefix=frontend/ install -g bower
  - npm --prefix=frontend/ install
  - cd frontend && bower install

script:
  ember --prefix=frontend/ test
